[package]
name = "screeps-arena-starter-rust"
version = "0.0.0"
authors = []
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3"
log = "0.4"
fern = "0.6"

[target.'cfg(target_arch = "wasm32")'.dependencies]
screeps-arena-wasm = { package = "screeps-arena-game-api", path = "../screeps-arena-game-api" }
wasm-bindgen-wasm = { package = "real-wasm-bindgen", path = "../arena_api_mock/real-wasm-bindgen" }
web-sys = { version = "0.3", features = ["console"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
screeps-arena-mock = { package = "mock-screeps-arena", path = "../arena_api_mock/mock-screeps-arena" }
wasm-bindgen-mock = { package = "wasm-bindgen", path = "../arena_api_mock/mock-wasm-bindgen" }


# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
# console_error_panic_hook = { version = "0.1.6", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
panic = "abort"
opt-level = 3
lto = true
debug = true

# wasm pack has a significant impact on binary size but adds some seconds to the build
# so it can be disabled
[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O4", "-g"]
#wasm-opt = false

[features]
default = []

season3-spawn_strike = [
  "screeps-arena-wasm/season3-spawn_strike",
  "screeps-arena-mock/season3-spawn_strike"
]
season3-power_split = [
  "screeps-arena-wasm/season3-power_split",
  "screeps-arena-mock/season3-power_split"
]
season3-escort_run = [
  "screeps-arena-wasm/season3-escort_run",
  "screeps-arena-mock/season3-escort_run"
]
