default_deploy_mode = "spawn"

[build]
build_mode = "arena"

[spawn]
destination = "/Users/username/ScreepsArena"
prune = false
branch = "season3-spawn_strike"
  [spawn.build]
  extra_options = ["--features=season3-spawn_strike"]

[power]
destination = "/Users/username/ScreepsArena"
prune = false
branch = "season3-power_split"
  [power.build]
  extra_options = ["--features=season3-power_split"]

[escort]
destination = "/Users/username/ScreepsArena"
prune = false
branch = "season3-escort_run"
  [escort.build]
  extra_options = ["--features=season3-escort_run"]

# for full syntax, see
# https://github.com/rustyscreeps/cargo-screeps/blob/master/screeps-defaults.toml
